name: UScore CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.14.3'

      - name: Restore dependencies cache
        id: uscore-mix-cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        if: steps.uscore-mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force && mix local.hex --force
          mix deps.get

      - name: Run tests
        run: mix test
